name: mercurio
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  page_flip: ^0.2.3
  shared_preferences: ^2.2.2
  xml: ^6.5.0
  dio: ^5.4.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
    - family: Carnevalee
      fonts:
        - asset: assets/fonts/Carnevalee-Freakshow.ttf
